version: 0.2

phases:
  install:
    commands:
      - echo ${CODEBUILD_BUILD_ID}
      - echo ${CODEBUILD_BUILD_ARN}
      - echo ${CODEBUILD_INITIATOR}
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo ${CODEBUILD_SOURCE_REPO_URL}
      - echo ${CODEBUILD_SOURCE_VERSION}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build -t ${REPOSITORY_URI}:latest .
  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:latest

